apiVersion : apps/v1
kind: Deployment 
metadata : 
  name: client-deployment
spec:
  replicas: 0
  selector: 
    matchLabels: 
      app: client
  template:
    metadata: 
      name: client-pods
      labels:
        app: client
    spec: 
      containers: 
        - name : client
          image: jonaswinkler/paperless-ng:latest